name: github-labels
description: Sync a repo's issue labels with Rowan Manning's standard set
inputs:
  github-token:
    description: The GitHub token used to sync labels
    required: true
runs:
  using: node12
  main: index.js
